services:
    postgres:
        container_name: postgres
        restart: always
        image: postgres
        ports:
          - 5432:5432
        volumes:
          - postgres:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=gooyi
          - POSTGRES_PASSWORD=gooyi
          - POSTGERS_DB=gooyi
          - POSTGERS_HOST_AUTH_METHOD=md55

    gooyi:
        build: .
        container_name: gooyi
        restart: always
        image: iamthienthanh/gooyi
        ports:
          - 8000:8000
        volumes:
          - gooyi:/app/logs/
        depends_on:
          - postgres
          # - cache

    redis:
        container_name: redis
        image: redis
        restart: always
        volumes:
          - cache:/data
        ports:
          - 6379:6379

    redis_insight:
        container_name: redis_insight
        image: redislabs/redisinsight:latest
        restart: always
        ports:
          - 8001:8001
        volumes:
          - redis_insight:/db

volumes:
  postgres:
  gooyi:
  cache:
  redis_insight: