version: '1.0'
services:
    postgres:
        container_name: postgres
        restart: always
        image: postgis/postgis
        ports:
          - 5432:5432
        volumes:
          - postgres:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=gooyi
          - POSTGRES_PASSWORD=gooyi
          - POSTGERS_DB=gooyi

    gooyi:
        build: .
        container_name: gooyi
        restart: always
        image: iamthienthanh/gooyi
        ports:
          - 8000:8000
        volumes:
          - gooyi:/app
        depends_on:
          - postgres

    redis:
        container_name: redis
        image: redis
        restart: always
        volumes:
          - cache:/data
        ports:
          - 6379:6379

volumes:
  postgres:
  gooyi:
  cache: