# Generated by Django 4.2.2 on 2023-06-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutcheinapp', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
