# Generated by Django 4.2.2 on 2023-06-19 23:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gutcheinapp', '0003_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVersuche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versucher', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
    ]
