# Generated by Django 4.2.2 on 2023-08-15 02:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gutcheinapp', '0005_rename_userid_userversuche_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmail',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('active', models.BooleanField(default=False)),
                ('expired', models.DateField()),
                ('type', models.CharField(choices=[('sold', 'Sold'), ('rewarded', 'Rewarded')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('detail', models.TextField()),
                ('type', models.CharField(choices=[('system', 'System'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('opening_hour', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='UserStorePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='SoldCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='RewardedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='MessageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='InactivityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('gift_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('level', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('unlocked', models.BooleanField()),
                ('achieved', models.BooleanField()),
                ('received', models.BooleanField()),
                ('redeemed', models.BooleanField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.coupon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='CouponBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.coupon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.store'),
        ),
    ]
