# Generated by Django 4.2.2 on 2023-08-15 02:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gutcheinapp', '0006_bannedemail_coupon_message_store_userstorepoint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='rating',
            new_name='average_rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('amount', models.FloatField()),
                ('method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_account', 'Bank Account'), ('paypal', 'PayPal')], max_length=15)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gutcheinapp.user')),
            ],
        ),
    ]
