# Generated by Django 4.2.2 on 2023-08-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutcheinapp', '0007_rename_rating_store_average_rating_rating_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_hour',
            field=models.CharField(),
        ),
    ]
