# Generated by Django 4.2.2 on 2023-08-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutcheinapp', '0008_alter_store_address_alter_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.CharField(default='0'),
        ),
        migrations.AddField(
            model_name='store',
            name='longtitude',
            field=models.CharField(default='0'),
        ),
    ]
