# Generated by Django 4.2.2 on 2023-08-28 16:27

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gutcheinapp', '0009_store_latitude_store_longtitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point((0, 0)), geography=True, srid=4326),
        ),
    ]
