const QUEST_TYPE = {
    VISIT_STORE: "VISIT_STORE",
    COLLECT_POINT: "COLLECT_POINT",
    PURCHASE: "PURCHASE",
    USE_COUPON: "USE_COUPON",
    COMPLETE: "COMPLETE",
    REWARD: "REWARD",
    LIKE_STORE: "LIKE_STORE",
    CUSTOMER_TYPE: "CUSTOMER_TYPE",
};
export default QUEST_TYPE;